services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/java-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready --username=postgres"
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java-db
      POSTGRES_PORT: 5432
